; ET37I - Sistemas Microcontrolados
; LABORATORIO 01 - PARTE 2: DOIS BOTOES ON/OFF

; CONFIGURAÇÕES
; Deve-se iniciar a linha abaixo com tabulação
  CONFIG  FOSC = HS, WDT = OFF, PBADEN = OFF
; FOSC = HS: Oscilador de 20MHz -> Tcy = 200ns
; WDT = OFF: WDT desabilitado
; PBADEN = OFF:  Pinos de PORTB [4:0] configurados como I/O digital.

#include <P18F4550.INC> ; MICROCONTROLADOR PIC18F4550

#define  BTN1  PORTB, 1
#define  BTN2  PORTB, 2
#define  LED1  PORTD, 0
#define  LED2  PORTD, 1

CBLOCK  0X00
  ATRASO
ENDC

  ORG  0x00
  GOTO  INICIO

; INICIO DO PROGRAMA
INICIO
  MOVLW  B'00000110'
  MOVLW  B'00000000'
  MOVWF  TRISD
  MOVWF  INTCON2
  MOVWF  INTCON

  BCF    LED1
  BCF    LED2

; ROTINA PRINCIPAL
MAIN_LOOP
  MOVLW  B'11111111' ; 255
  MOVWF  ATRASO

VERIFICA_BT1
  BTFSC   BTN1
  BRA     VERIFICA_BT2
  DECFSZ  ATRASO, F
  BRA     VERIFICA_BT1
  BRA     BOTAO1_INVERTE

BOTAO1_INVERTE
  BTFSC  LED1
  BRA    APAGA_LED_1
  BRA    ACENDE_LED_1

APAGA_LED_1
  BCF  LED1
  BRA  ESPERA_BT1

ACENDE_LED_1
  BSF  LED1
  BRA  ESPERA_BT1

ESPERA_BT1
  BTFSS  BTN1
  BRA    ESPERA_BT1
  BRA    MAIN_LOOP

VERIFICA_BT2
  BTFSC   BTN2
  BRA     MAIN_LOOP
  DECFSZ  ATRASO,F
  BRA     VERIFICA_BT2
  BRA     BOTAO2_INVERTE

BOTAO2_INVERTE
  BTFSC  LED2
  BRA    APAGA_LED_2
  BRA    ACENDE_LED_2

APAGA_LED_2
  BCF  LED2
  BRA  ESPERA_BT2

ACENDE_LED_2
  BSF  LED2
  BRA  ESPERA_BT2

ESPERA_BT2
  BTFSS  BTN2
  BRA    ESPERA_BT2
  BRA    MAIN_LOOP

  END
